# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lintnet < Formula
  desc "Secure, Powerful, Reusable Configuration file linter powered by Jsonnet
"
  homepage "https://github.com/lintnet/lintnet"
  version "0.4.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lintnet/lintnet/releases/download/v0.4.9/lintnet_darwin_amd64.tar.gz"
      sha256 "553d479d46a6af344ea1bf7bddaae5a19e9220e97ee112923624cd02591dd907"

      def install
        bin.install "lintnet"
        generate_completions_from_executable(bin/"lintnet", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lintnet/lintnet/releases/download/v0.4.9/lintnet_darwin_arm64.tar.gz"
      sha256 "ec75c9a8e5b324fec5a7616b96ee2e8f615ace83d8a56e3bf83d60667202570f"

      def install
        bin.install "lintnet"
        generate_completions_from_executable(bin/"lintnet", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lintnet/lintnet/releases/download/v0.4.9/lintnet_linux_amd64.tar.gz"
        sha256 "77405a4de92f61d804f41227306ca279e177f96bffb61b9b1908661c0c2ffc7d"

        def install
          bin.install "lintnet"
          generate_completions_from_executable(bin/"lintnet", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lintnet/lintnet/releases/download/v0.4.9/lintnet_linux_arm64.tar.gz"
        sha256 "c48b91c92834af40fdd3671e79531d8a4adae70cf1824c3bd5d4b734e3def5be"

        def install
          bin.install "lintnet"
          generate_completions_from_executable(bin/"lintnet", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/lintnet --version"
  end
end
