# This file was generated by GoReleaser. DO NOT EDIT.
cask "lintnet" do
  desc "Secure, Powerful, Reusable Configuration file linter powered by Jsonnet
"
  homepage "https://github.com/lintnet/lintnet"
  version "0.4.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lintnet"

  on_macos do
    on_intel do
      url "https://github.com/lintnet/lintnet/releases/download/v0.4.11/lintnet_darwin_amd64.tar.gz"
      sha256 "f201e9f1a573c8bf166025be7301ce9ad7a0661e08cd9c994273b6b61695b5ea"
    end
    on_arm do
      url "https://github.com/lintnet/lintnet/releases/download/v0.4.11/lintnet_darwin_arm64.tar.gz"
      sha256 "358a5add56607b3c45f65f86c47f5fee59d6688a2d50cee1b34b6407cfa33df0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lintnet/lintnet/releases/download/v0.4.11/lintnet_linux_amd64.tar.gz"
      sha256 "1c98cd93786e094988e4543ffa70069c56b471bae820791d0d71b04cf5460bda"
    end
    on_arm do
      url "https://github.com/lintnet/lintnet/releases/download/v0.4.11/lintnet_linux_arm64.tar.gz"
      sha256 "c2ad8ff6103ee7c1bf82f90046d8423e1a73deea64b4424150f5f4f75a24d5dd"
    end
  end

  # No zap stanza required
end
